name             'wp-cookbook'
maintainer       'BCNDojos'
maintainer_email 'bcndojos@example.com'
license          'MIT'
description      'Installs/Configures wp-cookbook'
long_description 'Installs/Configures wp-cookbook'
version          '0.1.0'

depends          'apt', '~> 2.6.1'
depends          'mysql', '<= 6.0.16'
